### ISSUE TITLE
Add support to release Linux AArch64/arm64 wheels

### ISSUE THREAD

**Issue by odidev** [fornwall/advent-of-code#10]
Problem
---------
On aarch64, ‘pip install advent-of-code’ gives the below error:
```
ERROR: Could not find a version that satisfies the requirement advent-of-code (from versions: none)
ERROR: No matching distribution found for advent-of-code
```

Even the source distribution is missing on PyPi. We can clone and do the installation from source code but it will be time consuming. Also, to build with the source code, users need to have the development environment installed on their machine.

Resolution
-----------
On aarch64, ‘pip install advent-of-code’ should download the wheels from pypi

@fornwall Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by fornwall** [comment]
I think your PR looks great, didn't know it was so smooth!

An initial release with aarch64 wheels has been pushed to pypi now, does it look fine?

**Comment by odidev** [comment]
Yes, I have done the basic testing and the wheel looks fine. Thanks
