### ISSUE TITLE
Day16 - Part1

### ISSUE THREAD

**Issue by scalonne** [fornwall/advent-of-code#30]
Following example prints 42 instead of 1:
|.........................................

**Comment by fornwall** [comment]
Are you sure you're not mixing up part 1 and 2?

Pushed a test here: https://github.com/fornwall/advent-of-code/commit/0849352d122fa2bf86fed86da09481ef91db2136 - as shown there the test asserts that the solution obtained from `|.........................................` is `1` for part 1, and `42` for part 2 - and the test passes.

**Comment by scalonne** [comment]
Oups my bad, I indeed forgot to change the part.
No problem then, my apologies and thanks for sharing your solution!
